from pathlib import Path

native = Path("src/lib/nativeDurableSnapshot.ts")
text = native.read_text()
old = '''  const primary = await readRaw(PRIMARY_PATH);\n  if (primary.status === "ok") {\n    const parsedPrimary = parseValidNotesSnapshot(primary.raw);\n    if (parsedPrimary !== null) return { status: "available", notes: parsedPrimary };\n  }\n\n  // primary が missing / corrupt / read error の場合でも backup は独立に読める可能性がある。\n  const backup = await readRaw(BACKUP_PATH);\n  if (backup.status === "ok") {\n    const parsedBackup = parseValidNotesSnapshot(backup.raw);\n    if (parsedBackup !== null) return { status: "available", notes: parsedBackup };\n  }\n\n  // rotation で退避した secondary も実際の復元経路へ含める。\n  // primary / backup の片方が I/O error や破損でも、secondary が正常なら読み取り専用候補として救済する。\n  const secondaryBackup = await readRaw(SECONDARY_BACKUP_PATH);\n  if (secondaryBackup.status === "ok") {\n    const parsedSecondaryBackup = parseValidNotesSnapshot(secondaryBackup.raw);\n    if (parsedSecondaryBackup !== null) {\n      return { status: "available", notes: parsedSecondaryBackup };\n    }\n  }\n\n  // 3層すべてから正常候補を得られなかった場合、I/O error または構造破損の痕跡が1つでもあれば\n  // fresh install と誤認せず error を返す。\n  if (\n    primary.status === "error" ||\n    backup.status === "error" ||\n    secondaryBackup.status === "error"\n  ) {\n    return { status: "error" };\n  }\n\n  if (\n    primary.status === "ok" ||\n    backup.status === "ok" ||\n    secondaryBackup.status === "ok"\n  ) {\n    return { status: "error" };\n  }\n\n  return { status: "missing" };'''
new = '''  const primary = await readRaw(PRIMARY_PATH);\n  if (primary.status === "error") {\n    // primary が読めない場合、より新しい正常世代が存在する可能性を否定できない。\n    // 古い backup を available として返すと silent rollback を確定可能にしてしまうため、\n    // 下位世代へ降りず safety check 未完了として扱う。\n    return { status: "error" };\n  }\n  if (primary.status === "ok") {\n    const parsedPrimary = parseValidNotesSnapshot(primary.raw);\n    if (parsedPrimary !== null) return { status: "available", notes: parsedPrimary };\n  }\n\n  // primary が missing または「読めたが破損」なら、より新しい正常世代が隠れている\n  // 不確実性はないため backup へ進める。\n  const backup = await readRaw(BACKUP_PATH);\n  if (backup.status === "error") {\n    // backup が読めない場合も、その世代が secondary より新しい可能性を否定できない。\n    return { status: "error" };\n  }\n  if (backup.status === "ok") {\n    const parsedBackup = parseValidNotesSnapshot(backup.raw);\n    if (parsedBackup !== null) return { status: "available", notes: parsedBackup };\n  }\n\n  // primary / backup が missing または明確な破損と確認できた場合だけ secondary へ進む。\n  const secondaryBackup = await readRaw(SECONDARY_BACKUP_PATH);\n  if (secondaryBackup.status === "error") {\n    return { status: "error" };\n  }\n  if (secondaryBackup.status === "ok") {\n    const parsedSecondaryBackup = parseValidNotesSnapshot(secondaryBackup.raw);\n    if (parsedSecondaryBackup !== null) {\n      return { status: "available", notes: parsedSecondaryBackup };\n    }\n  }\n\n  // 読めたファイルが1つでも構造破損なら fresh install ではない。\n  if (\n    primary.status === "ok" ||\n    backup.status === "ok" ||\n    secondaryBackup.status === "ok"\n  ) {\n    return { status: "error" };\n  }\n\n  return { status: "missing" };'''
if text.count(old) != 1:
    raise SystemExit(f"native read block marker: {text.count(old)}")
native.write_text(text.replace(old, new, 1))

primary_test = Path("src/lib/__tests__/nativeDurableSnapshot.test.ts")
t = primary_test.read_text()
old = '''  it("primary読込が一時失敗しても正常backupは読み取り専用の復元候補として返す", async () => {\n    const backup = [makeNote("backup")];\n    files.set(NATIVE_SNAPSHOT_PATHS_FOR_TESTING.backup, JSON.stringify(backup));\n    mocks.readFile.mockImplementation(async ({ path }: { path: string }) => {\n      if (path === NATIVE_SNAPSHOT_PATHS_FOR_TESTING.primary) {\n        throw { code: "OS-PLUG-FILE-0013" };\n      }\n      const data = files.get(path);\n      if (data === undefined) throw FILE_NOT_FOUND;\n      return { data };\n    });\n\n    expect(await readNativeDurableSnapshot()).toEqual({ status: "available", notes: backup });\n    expect(mocks.writeFile).not.toHaveBeenCalled();\n  });'''
new = '''  it("primary読込がI/O失敗なら古いbackupを確定可能な候補として返さない", async () => {\n    const backup = [makeNote("backup")];\n    files.set(NATIVE_SNAPSHOT_PATHS_FOR_TESTING.backup, JSON.stringify(backup));\n    mocks.readFile.mockImplementation(async ({ path }: { path: string }) => {\n      if (path === NATIVE_SNAPSHOT_PATHS_FOR_TESTING.primary) {\n        throw { code: "OS-PLUG-FILE-0013" };\n      }\n      const data = files.get(path);\n      if (data === undefined) throw FILE_NOT_FOUND;\n      return { data };\n    });\n\n    expect(await readNativeDurableSnapshot()).toEqual({ status: "error" });\n    expect(mocks.readFile).toHaveBeenCalledTimes(1);\n    expect(mocks.writeFile).not.toHaveBeenCalled();\n  });'''
if t.count(old) != 1:
    raise SystemExit(f"primary io fallback test marker: {t.count(old)}")
primary_test.write_text(t.replace(old, new, 1))

secondary_test = Path("src/lib/__tests__/nativeDurableSnapshot.secondary-recovery.test.ts")
s = secondary_test.read_text()
old = '''  it("primaryとbackupがI/O失敗でも正常secondaryがあれば救済する", async () => {\n    const secondary = [makeNote("secondary after io error")];\n    files.set(\n      NATIVE_SNAPSHOT_PATHS_FOR_TESTING.secondaryBackup,\n      JSON.stringify(secondary),\n    );\n    mocks.readFile.mockImplementation(async ({ path }: { path: string }) => {\n      if (\n        path === NATIVE_SNAPSHOT_PATHS_FOR_TESTING.primary ||\n        path === NATIVE_SNAPSHOT_PATHS_FOR_TESTING.backup\n      ) {\n        throw IO_ERROR;\n      }\n      const data = files.get(path);\n      if (data === undefined) throw FILE_NOT_FOUND;\n      return { data };\n    });\n\n    expect(await readNativeDurableSnapshot()).toEqual({\n      status: "available",\n      notes: secondary,\n    });\n  });'''
new = '''  it("primaryがI/O失敗なら正常secondaryがあっても安全確認未完了としてerrorにする", async () => {\n    const secondary = [makeNote("secondary after io error")];\n    files.set(\n      NATIVE_SNAPSHOT_PATHS_FOR_TESTING.secondaryBackup,\n      JSON.stringify(secondary),\n    );\n    mocks.readFile.mockImplementation(async ({ path }: { path: string }) => {\n      if (\n        path === NATIVE_SNAPSHOT_PATHS_FOR_TESTING.primary ||\n        path === NATIVE_SNAPSHOT_PATHS_FOR_TESTING.backup\n      ) {\n        throw IO_ERROR;\n      }\n      const data = files.get(path);\n      if (data === undefined) throw FILE_NOT_FOUND;\n      return { data };\n    });\n\n    expect(await readNativeDurableSnapshot()).toEqual({ status: "error" });\n    expect(mocks.readFile).toHaveBeenCalledTimes(1);\n  });'''
if s.count(old) != 1:
    raise SystemExit(f"secondary primary io test marker: {s.count(old)}")
s = s.replace(old, new, 1)
marker = '''  it("primaryとbackup不存在でもsecondary読込失敗はfresh install扱いしない", async () => {'''
extra = '''  it("primary不存在でもbackupがI/O失敗なら正常secondaryへ降りずerrorにする", async () => {\n    const secondary = [makeNote("secondary behind unreadable backup")];\n    files.set(\n      NATIVE_SNAPSHOT_PATHS_FOR_TESTING.secondaryBackup,\n      JSON.stringify(secondary),\n    );\n    mocks.readFile.mockImplementation(async ({ path }: { path: string }) => {\n      if (path === NATIVE_SNAPSHOT_PATHS_FOR_TESTING.primary) throw FILE_NOT_FOUND;\n      if (path === NATIVE_SNAPSHOT_PATHS_FOR_TESTING.backup) throw IO_ERROR;\n      const data = files.get(path);\n      if (data === undefined) throw FILE_NOT_FOUND;\n      return { data };\n    });\n\n    expect(await readNativeDurableSnapshot()).toEqual({ status: "error" });\n    expect(mocks.readFile).toHaveBeenCalledTimes(2);\n  });\n\n'''
if s.count(marker) != 1:
    raise SystemExit(f"secondary unreadable backup marker: {s.count(marker)}")
secondary_test.write_text(s.replace(marker, extra + marker, 1))
